### ISSUE TITLE
NPC jump every time path:Run() is called

### ISSUE THREAD

**Issue by dogevspenguin** [00xima/SimplePath#1]
NPC jump every time path:Run() is called

**Comment by 00xima** [comment]
Could I see a gif or a video of the behaviour?

**Comment by dogevspenguin** [comment]
Well sorry i can't but to describe,Essencially every time path:run() is called like 
while true do
path:Run() 
wait(0.5)
end
the npc will jump when the path:Run()  is called so every 0.5 sec

**Comment by 00xima** [comment]
I can't really do much without seeing a visual because I can't replicate the issue.

**Comment by dogevspenguin** [comment]
https://vimeo.com/manage/videos/551308642 on the example it don't jump

**Comment by 00xima** [comment]
Can't access the video

**Comment by dogevspenguin** [comment]
Hmm i'll send an embedded gif then

**Comment by dogevspenguin** [comment]
![Uploading Zambie.mov-low.gif…]()

**Comment by dogevspenguin** [comment]
![Zambie mov-low](https://user-images.githubusercontent.com/62637922/118431092-cb614f80-b6ff-11eb-91f3-4c331e684e42.gif)

**Comment by 00xima** [comment]
Hmm, are you able to provide the rblx file of the issue; it will help examine the issue.

**Comment by dogevspenguin** [comment]
Ok

**Comment by dogevspenguin** [comment]
[Backroom copy.rbxl.zip](https://github.com/00xima/SimplePath/files/6491052/Backroom.copy.rbxl.zip)

**Comment by 00xima** [comment]
The reason why it was jumping is that the module takes into account the HipHeight of the humanoid. But since the HipHeight of your rig was 0, it was miscalculating the jump. To fix this, just use the new added method `Path:SetHipHeight()`. The HipHeight for the rig you are using would be 2.

**Comment by dogevspenguin** [comment]
Well thank you for the clarification,And since i can't post reply on your topic in the dev forum(Im new on that)I will post it here that your module is awesome.
