### ISSUE TITLE
Extra function request

### ISSUE THREAD

**Issue by supremebloxboy** [00xima/SimplePath#4]
Can you add a function to get path waypoints, ex: path:GetWaypoints(), would be useful for situations when manual pathing is necessary. I had a situations where I was creating multiple paths on the same npc and comparing to find the best path and I needed to get the waypoints of the paths. Also side note, is there a way to add a function to ignore objects when generating paths, like a function similar to Raycast ignorelist? the npc was interfering with the paths. Anyhow Thanks!

**Comment by Baileyeatspizza** [comment]
you should be able to do

```lua
local success = path:Run()
if success then
     local Waypoints = path._waypoints
     local CurrentWaypoint = _currentWaypoint
end
```

but for your use case it might be worth trying [Roblox's pathfinding modifiers](https://developer.roblox.com/en-us/articles/Pathfinding#pathfinding-modifiers) to make the path avoid those npcs
